# Generated by Django 4.1.6 on 2023-02-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Purple'), ('Y', 'Yellow'), ('O', 'Orange'), ('B', 'Blue'), ('G', 'Green')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stone',
            name='numberOfAppearances',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Weilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('is_hero', models.BooleanField()),
                ('phase_of_use', models.PositiveSmallIntegerField()),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stone')),
            ],
        ),
    ]
