# Generated by Django 4.1.6 on 2023-02-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_stone_color_alter_stone_numberofappearances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Purple'), ('Y', 'Yellow'), ('O', 'Orange'), ('B', 'Blue'), ('G', 'Green')], default='Red', max_length=100),
        ),
    ]
