# Generated by Django 4.1.6 on 2023-02-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_weilder_is_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weilder',
            name='is_hero',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
