# Generated by Django 4.1.6 on 2023-02-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_weilder_is_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_ensemble', models.BooleanField(choices=[(True, 'Ensemble'), (False, 'Solo')], default=True, verbose_name='Ensemble or Solo Film')),
                ('release_date', models.DateField(verbose_name='Release Year')),
            ],
        ),
        migrations.AlterModelOptions(
            name='weilder',
            options={'ordering': ['-phase_of_use', 'character', 'is_hero']},
        ),
    ]
