# Generated by Django 4.1.6 on 2023-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_movie_alter_weilder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.AddField(
            model_name='stone',
            name='movies',
            field=models.ManyToManyField(to='main_app.movie'),
        ),
    ]
